config/routes.rb
Rails.application.routes.draw do
  resources :cartao_pedidos
  resources :cartaos
  resources :pedidos
  resources :entregadors
  get 'sessions/new'
  resources :users

  resources :restaurantes do
    resources :pratos
  end
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'restaurantes#index', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'entrance', to: 'home#index', as: 'entrance'

  root 'sessions#new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/restaurante.rb
class Restaurante < Database
  include ActiveModel::Model
  attr_accessor :id, :cnpj, :nome_fantasia, :nome_oficial, :phone, :horario, :tipo_comida, :endereco, :created_at, :updated_at

  # has_many :pratos

  def pratos
    Prato.where(restaurante_id: self.id)
  end

  TABLENAME = 'restaurantes'
end

app/controllers/restaurantes_controller.rb
class RestaurantesController < ApplicationController
  before_action :set_restaurante, only: [:show, :edit, :update, :destroy]
  # before_action :authorize

  # GET /restaurantes
  # GET /restaurantes.json
  def index
    @restaurantes = Restaurante.all
  end

  # GET /restaurantes/1
  # GET /restaurantes/1.json
  def show

  end

  # GET /restaurantes/new
  def new
    @restaurante = Restaurante.new
  end

  # GET /restaurantes/1/edit
  def edit
  end

  # POST /restaurantes
  # POST /restaurantes.json
  def create
    @restaurante = Restaurante.new(restaurante_params)

    respond_to do |format|
      if @restaurante.save
        format.html { redirect_to @restaurante, notice: 'Restaurante was successfully created.' }
        format.json { render :show, status: :created, location: @restaurante }
      else
        format.html { render :new }
        format.json { render json: @restaurante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurantes/1
  # PATCH/PUT /restaurantes/1.json
  def update
    respond_to do |format|
      if @restaurante.update(restaurante_params)
        format.html { redirect_to @restaurante, notice: 'Restaurante was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurante }
      else
        format.html { render :edit }
        format.json { render json: @restaurante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurantes/1
  # DELETE /restaurantes/1.json
  def destroy
    @restaurante.destroy
    respond_to do |format|
      format.html { redirect_to restaurantes_url, notice: 'Restaurante was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurante
      @restaurante = Restaurante.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurante_params
      params.require(:restaurante).permit(:cnpj, :nome_oficial, :nome_fantasia, :phone, :horario, :tipo_comida, :endereco)
    end

    def authorize
      head :unauthorized if !current_user
    end
end

app/helpers/restaurantes_helper.rb
module RestaurantesHelper
end

app/views/restaurantes/_form.html.erb
<%= form_with(model: restaurante, local: true) do |form| %>
  <% if restaurante.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurante.errors.count, "error") %> prohibited this restaurante from being saved:</h2>

      <ul>
        <% restaurante.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :cnpj %>
    <%= form.text_field :cnpj %>
  </div>

  <div class="field">
    <%= form.label :nome_oficial %>
    <%= form.text_field :nome_oficial %>
  </div>

  <div class="field">
    <%= form.label :nome_fantasia %>
    <%= form.text_field :nome_fantasia %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :horario %>
    <%= form.text_field :horario %>
  </div>

  <div class="field">
    <%= form.label :tipo_comida %>
    <%= form.text_field :tipo_comida %>
  </div>

  <div class="field">
    <%= form.label :endereco %>
    <%= form.text_field :endereco %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/restaurantes/edit.html.erb
<h1>Editing Restaurante</h1>

<%= render 'form', restaurante: @restaurante %>

<%= link_to 'Show', @restaurante %> |
<%= link_to 'Back', restaurantes_path %>

app/views/restaurantes/index.html.erb
<% @restaurantes.each do |restaurante| %>

  <div class="card" style="width: 60rem; margin: 20px auto;">
    <div class="card-body">
      <h4 class="card-title">  <%= restaurante.nome_fantasia %></h4>
      <h6 class="card-subtitle mb-2 text-muted"><%= restaurante.tipo_comida %></h6>
      <p class="card-text">Horário de funcionamento: <%= restaurante.horario %>.</p>
      <%= link_to restaurante_pratos_path(restaurante_id: restaurante.id) do %>
        <button type="button" class="btn btn-danger">Menu</button>
      <% end %>
    </div>
  </div>

<% end %>

app/views/restaurantes/new.html.erb
<h1>New Restaurante</h1>

<%= render 'form', restaurante: @restaurante %>

<%= link_to 'Back', restaurantes_path %>

app/views/restaurantes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cnpj:</strong>
  <%= @restaurante.cnpj %>
</p>

<p>
  <strong>Nome oficial:</strong>
  <%= @restaurante.nome_oficial %>
</p>

<p>
  <strong>Nome fantasia:</strong>
  <%= @restaurante.nome_fantasia %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @restaurante.phone %>
</p>

<p>
  <strong>Horario:</strong>
  <%= @restaurante.horario %>
</p>

<p>
  <strong>Tipo comida:</strong>
  <%= @restaurante.tipo_comida %>
</p>

<p>
  <strong>Adress:</strong>
  <%= @restaurante.endereco %>
</p>

<%= link_to 'Back', restaurantes_path %>