config/routes.rb
Rails.application.routes.draw do
  resources :cartao_pedidos
  resources :cartaos
  resources :pedidos
  resources :entregadors
  get 'sessions/new'
  resources :users

  resources :restaurantes do
    resources :pratos
  end
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'restaurantes#index', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'entrance', to: 'home#index', as: 'entrance'

  root 'sessions#new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/pedido.rb
class Pedido < Database
  include ActiveModel::Model
  attr_accessor :prato_id, :id, :user_id, :forma_pagamento, :troco, :entregador_id, :created_at, :updated_at


  def prato
    Prato.find(self.prato_id)
  end



  def entregador
    Entregador.find(self.entregador_id)
  end

  # belongs_to :prato
  # belongs_to :user
  # belongs_to :entregador

  TABLENAME = 'pedidos'

end

app/controllers/pedidos_controller.rb
class PedidosController < ApplicationController
  before_action :set_restaurante
  before_action :set_prato

  # GET /pedidos
  # GET /pedidos.json
  def index
    @pedidos = Pedido.all
  end

  # GET /pedidos/1
  # GET /pedidos/1.json
  def show
    @pedido = Pedido.find(params[:id])
  end

  # GET /pedidos/new
  def new
    @pedido = Pedido.new
  end

  # GET /pedidos/1/edit
  def edit
  end

  # POST /pedidos
  # POST /pedidos.json
  def create
    @pedido = Pedido.new(pedido_params)

    credit_card_id = create_credit_card if pedido_params[:forma_pagamento] == '0'

    respond_to do |format|
      if @pedido.save

        if credit_card_id
          CartaoPedido.create(cartao_id: credit_card_id, pedido_id: @pedido.id)
        end

        format.html { redirect_to pedido_path(id: @pedido.id), notice: 'Pedido was successfully created.' }
        format.json { render :show, status: :created, location: @pedido }
      else
        format.html { render :new }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  private

    def set_prato
      @prato = Prato.find(params[:prato_id].to_i)
    end

    def set_restaurante
      @restaurante = Restaurante.find(params[:restaurante_id].to_i)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pedido_params
      params.require(:pedido).permit(:prato_id, :forma_pagamento, :troco, :entregador_id, :user_id)
    end

    def create_credit_card
      Cartao.create(params[:'credit-card'].merge(user_id: pedido_params[:user_id]))
    end
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/views/pedidos/_credit_card.html.erb
<section id="credit-card-fields" class="d-none">
  <div class="field">
    <label>Número</label>
    <input type="text" name="credit-card[numero]" id="credit-card-number" />
  </div>

  <div class="field">
    <label>Titular</label>
    <input type="text" name="credit-card[nome_titular]" id="credit-card-name" />
  </div>

  <div class="field">
    <label>Data de vencimento</label>
    <input type="text" name="credit-card[validade]" id="credit-card-validate" />
  </div>
</section>

app/views/pedidos/_form.html.erb
<section id="pedido-container">
  <%= form_with(model: pedido, local: true) do |form| %>
    <% if pedido.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(pedido.errors.count, "error") %> prohibited this pedido from being saved:</h2>

        <ul>
          <% pedido.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <input type="hidden" name="restaurante_id", value=<%= @restaurante.id %> />
    <input type="hidden" name="prato_id", value=<%= @prato.id %> />

    <div class="field d-none">
      <%= form.label :prato_id %>
      <%= form.text_field :prato_id, value: params['prato_id'] %>
    </div>

    <div class="field d-none">
      <%= form.label :user_id %>
      <%= form.text_field :user_id, value: current_user.id %>
    </div>

    <div class="field">
      <label>Forma de pagamento:</label>
      <%= form.select :forma_pagamento, options_for_select([['Dinheiro', '1'], ['Cartão', '0']]), {}, class: 'custom-select mr-sm-2' %>
    </div>

    <%= render 'credit_card' %>
    <br>
    <%= render 'money', form: form %>

    <div class="field d-none">
      <%= form.label :entregador_id %>
      <%= form.text_field :entregador_id, value: Entregador.all.first.id %>
    </div>

    <br>
    <div class="actions">
      <%= form.submit class: 'btn btn-danger', id: 'place-order' %>
    </div>
  <% end %>
</section>

app/views/pedidos/_money.html.erb
<section id="money-fields">
  <div class="field">
    <%= form.label 'Precisa de troco?' %>
    <%= form.check_box :troco %> Sim
  </div>
</section>

app/views/pedidos/edit.html.erb
<h1>Editing Pedido</h1>

<%= render 'form', pedido: @pedido %>

<%= link_to 'Show', @pedido %> |
<%= link_to 'Back', pedidos_path %>

app/views/pedidos/new.html.erb
<h1>Realizar Pedido</h1>

<%= render 'form', pedido: @pedido %>

<%= link_to restaurantes_path do %>
  <button type="button" class="btn btn-danger">Voltar para a lista de restaurantes</button>
<% end %>

app/views/pedidos/show.html.erb
<p id="notice"><%= notice %></p>

<% prato = @pedido.prato %>

<h4> Descrição </h4>
<p>
  <strong>Prato:</strong>
  <%= prato.descricao %>
</p>

<p>
  <strong>Tempo estimado:</strong>
  <%= prato.tempo_estimado %>
</p>

<h3> Entregador </h3>

<% entregador = @pedido.entregador %>

<p>
  <strong>Nome:</strong>
  <%= entregador.nome %>
</p>

<p>
  <strong>Veículo:</strong>
  <%= entregador.veiculo %>
</p>

<p>
  <strong>Placa:</strong>
  <%= entregador.placa %>
</p>

<p>
  <strong>Troco:</strong>
  <%= @pedido.troco %>
</p>

<p>
  <strong>Entregador:</strong>
  <%= @pedido.entregador_id %>
</p>

<%= link_to restaurantes_path do %>
  <button type="button" class="btn btn-danger">Voltar para a lista de restaurantes</button>
<% end %>