config/routes.rb
Rails.application.routes.draw do
  resources :cartao_pedidos
  resources :cartaos
  resources :pedidos
  resources :entregadors
  get 'sessions/new'
  resources :users

  resources :restaurantes do
    resources :pratos
  end
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'restaurantes#index', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'entrance', to: 'home#index', as: 'entrance'

  root 'sessions#new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/prato.rb
class Prato < Database
  include ActiveModel::Model
  attr_accessor :id, :descricao, :preco, :disponibilidade, :tempo_estimado, :restaurante_id, :created_at, :updated_at

  TABLENAME = 'pratos'

  # belongs_to :restaurante
end

app/controllers/pratos_controller.rb
class PratosController < ApplicationController
  before_action :set_prato, only: [:show, :edit, :update, :destroy]
  before_action :set_restaurante

  # GET /pratos
  # GET /pratos.json
  def index
    @pratos = @restaurante.pratos
  end

  # GET /pratos/1
  # GET /pratos/1.json
  def show
  end

  # GET /pratos/new
  def new
    @prato = Prato.new
  end

  # GET /pratos/1/edit
  def edit
  end

  # POST /pratos
  # POST /pratos.json
  def create
    @prato = Prato.new(prato_params)

    respond_to do |format|
      if @prato.save
        format.html { redirect_to restaurante_prato_path(restaurante_id: @restaurante.id, id: @prato.id), notice: 'prato criado.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /pratos/1
  # PATCH/PUT /pratos/1.json
  def update
    respond_to do |format|
      if @prato.update(prato_params)
        format.html { redirect_to @prato, notice: 'prato atualizado.' }
        format.json { render :show, status: :ok, location: @prato }
      else
        format.html { render :edit }
        format.json { render json: @prato.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pratos/1
  # DELETE /pratos/1.json
  def destroy
    @prato.destroy
    respond_to do |format|
      format.html { redirect_to restaurante_pratos_path(restaurante_id: @restaurante.id), notice: 'prato apagado com sucesso.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prato
      @prato = Prato.find(params[:id])
    end

    def set_restaurante
      @restaurante = Restaurante.find(params[:restaurante_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prato_params
      params.require(:prato).permit(:descricao, :preco, :disponibilidade, :tempo_estimado, :restaurante_id)
    end
end

app/helpers/pratos_helper.rb
module PratosHelper
end

app/views/pratos/_admin_buttons.html.erb
<td><%= link_to 'Ver', restaurante_prato_path(restaurante_id: @restaurante.id, id: prato.id) %></td>
<td><%= link_to 'Editar', edit_restaurante_prato_path(restaurante_id: @restaurante.id, id: prato.id) %></td>
<td><%= link_to 'Apagar', restaurante_prato_path(restaurante_id: @restaurante.id, id: prato.id), method: :delete, data: { confirm: 'Tem certeza?' } %></td>

app/views/pratos/_form.html.erb
<%= form_with(model: prato, url: url, local: true, method: method) do |form| %>
  <% if prato.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(prato.errors.count, "error") %> prohibited this prato from being saved:</h2>

      <ul>
        <% prato.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :descricao %>
    <%= form.text_field :descricao %>
  </div>

  <div class="field">
    <%= form.label :preco %>
    <%= form.text_field :preco %>
  </div>

  <div class="field">
    <%= form.label :tempo_estimado %>
    <%= form.text_field :tempo_estimado %>
  </div>

  <div class="field d-none">
    <%= form.label :restaurante_id %>
    <%= form.text_field :restaurante_id, value: restaurante.id %>
  </div>

  <div class="field">
    <%= form.check_box :disponibilidade %> Prato disponível
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pratos/edit.html.erb
<h1>Edição de prato</h1>

<%= render 'form', restaurante: @restaurante, prato: @prato, url: restaurante_prato_path(restaurante_id: @restaurante.id, id: prato.id), method: 'PATCH' %>

<%= link_to 'Mostrar', @prato %> |
<%= link_to 'Voltar', pratos_path %>

app/views/pratos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pratos do restaurante <%= @restaurante.nome_fantasia %></h1>

<% @pratos.each do |prato| %>


  <div class="card" style="width: 60rem; margin: 20px auto;">
    <div class="card-body">
      <h4 class="card-title">  <%= prato.descricao %></h4>
      <h6 class="card-subtitle mb-2 text-muted"><%= number_to_currency(prato.preco) %></h6>
      <p class="card-text">Disponível: <%= prato.disponibilidade ? 'Sim' : 'Não' %></p>
      <%= link_to new_pedido_path(restaurante_id: @restaurante.id, prato_id: prato.id) do %>
        <button type="button" class="btn btn-danger">Pedir</button>
      <% end %>
    </div>
  </div>
<% end %>

app/views/pratos/new.html.erb
<h1>Novo prato</h1>

<%= render 'form', restaurante: @restaurante, prato: @prato, url: restaurante_pratos_path(restaurante_id: @restaurante.id), method: 'POST' %>

<%= link_to 'Back', restaurante_pratos_path %>

app/views/pratos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descricao:</strong>
  <%= @prato.descricao %>
</p>

<p>
  <strong>Preco:</strong>
  <%= number_to_currency(@prato.preco) %>
</p>

<p>
  <strong>Disponibilidade:</strong>
  <%= @prato.disponibilidade ? 'Sim' : 'Não' %>
</p>

<p>
  <strong>Tempo estimado:</strong>
  <%= @prato.tempo_estimado %>
</p>

<p>
  <strong>Restaurante:</strong>
  <%= @restaurante.nome_oficial %> (<%= @restaurante.nome_fantasia %>)
</p>

<%= link_to 'Editar', edit_restaurante_prato_path(restaurante_id: @restaurante.id, id: @prato.id) %> |
<%= link_to 'Voltar', restaurante_pratos_path(restaurante_id: @restaurante.id) %>